apiVersion: v1
kind: ConfigMap
metadata:
  name: snr-dvops-job-configs
  namespace: devops-and-networking-team
data:
  company-description: |+
    Ranked on Deloittes Fast 50 and Fast 500 lists 4 years in a row,\n 
    AcuityAds is one of the fastest-growing technology companies in North America as well\n
    as Europe in the programmatic marketing space which is the fastest-growing segment of\n
    digital advertising in the world today. Acuity empowers marketers by offering transparency\n 
    on costs and brand safety, and real-time reporting and analytics, bringing accountability\n
    to programmatic advertising to deliver business results. AcuityAds is headquartered in\n
    Toronto, Canada with sales offices in New York City, Boston, Chicago, Los Angeles,\n
    San Francisco, San Diego, Vancouver, Calgary, Montreal, and Europe.

    AcuityAds recently launched a revolutionary new advertising platform, meet illumin - for more\n 
    info go to www.illumin.com.
  job-overview: |+
    We are looking for someone who loves technology, really gets and understands DevOps and\n
    how to define, manage and deliver projects that will increase the DevOps maturity accountability\n
    AcuityAds. The team is currently made up 3 very talented engineers, who are currently preparing\n
    to embark on a year long mission to change the way we deliver value to our customers.\n
    Creating a clear line of sight to our customers for Acuity's development, big data and data science\n
    teams and creating innovative tools to allow any Acuitian to consume resources in our private cloud,\n
    offering the same experience provided to users by any public cloud provider.\n\n

    Some projects from the road map this year:\n
      - Revamp of the build and deployment pipelines\n
      - Introduction of new tooling to refine development and ITSM practices\n
      - Revamp of monitoring and observability practices and tooling\n
        including more advanced monitoring for our new data center facilities\n
      - Introduction to a custom k8s operator for handling state changes in our private cloud.\n
      - Re-design of our large production kubernetes cluster\n
      - Introduction of network automation and pipelines to deploy changes\n
      - Implementation of a new fully automated central auth system for our data centers.

    The team does work on a weekly on-call rotation schedule for any major incidents that\n
    occur with critical system.

    Please be prepared to talk in-depth during the interview process about new technologies that\n
    has excited you recently.

    Our goal is to be able to make our developers and engineers feel like they can\n
    have and idea, no matter how big and make it happen. We also want to help set a\n
    standard for DevOps teams and tech companies across Toronto to aspire.

    So, do you want to be apart of what is going to be an amazing year not just for the DevOps\n
    team, but for the revolutionary technology company that is AcuityAds.
immutable: true
---
apiVersion: v1
kind: Secret
metadata:
  name: snr-dvops-job-comp-secret
  namespace: devops-and-networking-team
type: Opaque
data:
  comp: Q29tcGV0aXRpdmUgYW5kIFJld2FyZGluZy4gWW91IHNob3VsZCBjb21lIGFuZCB3b3JrIGZvciB1cyBpZiB5b3UgdGhp
        bmsgeW91IGhhdmUgd2hhdCBpdCB0YWtlcwo=
---
apiVersion: jobs.acuityads.cloud/v1
kind: DevopsEngineer
metadata:
  name: senior-devops-engineer
  namespace: devops-and-networking-team
  annotations: 
    "acuityads/contact-name": "Thomas Sampson"
    "acuityads/contact-email": "thomas.sampson@acuityads.com"
spec:
  image: acuityads.cloud/devops-operator:latest
  companySpec:
    company: AcuityAds Inc
    industry: Advertising Technology
    location: Toronto, ON
    description:
      valueFrom:
        configMapKeyRef:
          name: snr-dvops-job-configs
          key: company-description
    benefits:
      - Unlimited Vacation
      - A fully stocked and functioning kitchen
      - Structured employee recognition awards and financial wellness programs.
      - In-house registered massage therapy service
      - Great Health Benefits with enhanced vision and dental
  nodeSelector:
    work-mentality: TeamPlayer
    motivated: true
    problemSolvingMode: innovative
  jobSpec:
    title: Senior DevOps Engineer
    location: ["Toronto, ON"]
    reportingTo: 
      title: Manager, Operations
      department: DevOps & Networking
    onCall: true
    overview:
      valueFrom:
        configMapKeyRef:
          name: snr-dvops-job-configs
          key: job-overview
    essentialSkills:
      - Ability to come up with innovative solutions to interesting and challenging problems
      - Experience with managing projects end-to-end that deliver value to colleagues and customers
      - Strong Knowledge of DevOps Methodologies and how to apply them
      - Expert Knowledge of Kubernetes in production deployments
      - Good knowledge of containerization technologies such as Docker
      - Good knowledge of Linux server administration, CentOS/RHEL or Ubunutu desirable
      - Experience with provisioning infrastructure with tooling such as Terraform
      - Configuration management of hosts using tooling such as Ansible, Chef or Puppet
      - Good knowledge of VMWare and virtualized technologies
      - Ability to help grow and mature a team of talented DevOps engineers both technically and professionally
      - Experience with creating reliable and sleek CI/CD pipelines for developers to enjoy
      - Strong knowledge of at least one programming language, preferred GoLang, Python, JavaScript, Bash
      - Strong experience using Git and designing effective git flows.
    desirableSkills:
      - Knowledge of Data Center and Private Cloud Operations
      - Experience working with external vendors
      - Working knowledge of ITIL service management
      - Experience developing custom kubernetes operators and CRD's
      - Working knowledge of Agile/Kanban development methodologies
      - Knowledge of implementing network automation into development pipelines
    technologies:
      cloudSpec:
        type: Private
        averageInboundRequestsPerSeconds: 1000000
        locations: ["Los Angeles, CA", "Herndon, VA", "Amsterdam, NL"]
        usePublicCloud: false
      applicationStack: ["Java", "ReactJS", "TypeScript", "Python", "Scala"]
      tooling: ["Bamboo","Bitbucket","Jira", "Nagios", "ELK", "Grafana", "PagerDuty", "Cobbler", "HashiCorp Boundary"]
      databases: ["AeroSpike", "MySql", "PostgreSql", "Cassandra", "InfluxDB", "HBASE"]
      bigData: ["Druid", "Hadoop 3.0", "Apache Spark", "Zeppelin", "Jupyter"]
      compute: ["ESXi", "Kubernetes", "Physical Hosts", "Docker", "CentOS"]
      networking: ["Cisco (10Gbps Network)", "A10 Load Balancers", "HashiCorp Consul"]
    compensation:
      valueFrom:
          secretKeyRef:
            name: snr-dvops-job-comp-secret
            key: comp